### ISSUE TITLE
Fresh Ubuntu 22.04 installation for Autoware

### ISSUE THREAD

**Issue by zcdai** [Monash-Connected-Autonomous-Vehicle/modified-autoware.universe#2]
Clearance has been given to use the 500Gb HDD on The Beast, which currently has windows installed on it.

While doing this, ensure you don't wipe the 2TB NAS!

Purpose of this project is to see if a fresh installation of Ubuntu 22.04 will make installing Autoware easier in terms of resolving dependencies.

**Comment by andSoHenceforth** [comment]
Attempted to wipe 500GB drive using terminal commands. Was careful not to wipe 2TB drive.
All partitions have been removed from sdb (the 500GB drive)
But I'm mostly sure that it hasn't been properly wiped, errors appear when using shred command
Linux *Ubuntu 22.04) is still needed to be installed

![Image](https://github.com/Monash-Connected-Autonomous-Vehicle/modified-autoware.universe/assets/110092516/1e97247c-8800-4e38-8a22-213e1c546ae5)
![Image](https://github.com/Monash-Connected-Autonomous-Vehicle/modified-autoware.universe/assets/110092516/c9ffba5a-2ee5-40cd-bcf2-db019cdcc0dd)
![Image](https://github.com/Monash-Connected-Autonomous-Vehicle/modified-autoware.universe/assets/110092516/8d05eff2-a4d6-431b-9e98-2170a57edeee)

@hubdwoo If you see this, could you let me know if I'm wiping off the drive properly or if there's anything else I need to do to wipe the drive properly? This is my first time wiping a drive off a computer so I wasn't sure if I was doing it right

**Comment by hubdwoo** [comment]
@adar0024 According to your first screenshot. It seems that there isn't any partition table for /dev/sdb. My guess is that someone probably wiped it off before.

From what I know, Input/Output error usually happens because of hardware or the use of NTFS(cause drivers are unstable according to [this](https://unix.stackexchange.com/questions/39905/input-output-error-when-accessing-a-directory). 

But I do not think that this is the case right now. I believe this is because there isn't any partition table inside the drive that means that it doesn't have the map of where things are. So, I think that's why it raised that error because you can't delete something that doesn't exist.

I am not 100% sure of how shred works. Just used it a couple of times but not sure why the first one works. The errors raised make sense because shred essentially replacing previous allocated data to scramble it. Because when you delete something you just delete the inode(something like a pointer) and the data is left untouched but the use of shred helps to make sure that the block is actually deleted by setting values to some value and repeating that process make sure that the data is unrecoverable. But in the case where it doesn't have partition table, there's no partition to access. I do not think shred is necessary if you just want to add some extra storage for the beast.



### Option 1: Add for storage
If you want to add more storage to the beast. You can use the gparted or fdisk whichever you prefer. Create a partition table add a partition and just format it with ext4 filesystem(I recommend btrfs but again it requires a little bit more work & its considered a 'new' filesystem because its the youngest out of all. But I like it and I wish I use it more often cuz it has snapshots like Copy-on-write thing :D). Then, just mount that to a directory. 

You can make sure that its automatically mounted by modifying the /etc/fstab file and specify it there but be careful if you incorrectly specify things inside fstab or if you someday took out the drive, it (in most cases) failed to boot up but you can fix it easily by going to recovery mode and remove the line but yeah just be careful.



### Option 2: Install a fresh 22.04 LTS (Btw there's new Ubuntu 23.04 :D)
Just use rufus or etcher or dd(if you feel you need a challenge) to burn the Ubuntu 22.04 iso into a flash drive. Then just use that flash drive plug it into the beast, boot to that usb and just follow a the step-by-step instruction.

Hope this helps!

**Comment by andSoHenceforth** [comment]
Hey Hubert, thanks for your insightful explanation!
I am going with Option 2 as Jason asked me to do in the AWSIM meeting yesterday. I was just wondering which settings in rufus I need to choose below before I burn the Ubuntu into a flash drive

![Screenshot 2023-10-16 225654](https://github.com/Monash-Connected-Autonomous-Vehicle/modified-autoware.universe/assets/110092516/241262a9-28df-4052-a629-81d0aeaade9b)

**Comment by zcdai** [comment]
Leaving the options on default should be fine.

**Comment by andSoHenceforth** [comment]
![ubunut](https://github.com/Monash-Connected-Autonomous-Vehicle/modified-autoware.universe/assets/110092516/12a6a5df-bd26-4783-bc99-0c17c35df81f)
Thanks, this is what my USB drive looks like now, should be all good now to plug the drive into the Beast and install today

**Comment by andSoHenceforth** [comment]
![IMG_7566](https://github.com/Monash-Connected-Autonomous-Vehicle/mcav-autoware.universe/assets/110092516/c9f41268-bf35-4333-9108-ba181da7a90d)
![IMG_7568](https://github.com/Monash-Connected-Autonomous-Vehicle/mcav-autoware.universe/assets/110092516/20158ab1-1c08-4472-8dbe-78242ded33ee)
Went into the same input/output error when trying to erase the disk and then install Ubuntu. It's also stuck on this error message and I can't get out of it

**Comment by adar0024** [comment]
![IMG_7566](https://github.com/Monash-Connected-Autonomous-Vehicle/mcav-autoware.universe/assets/110092516/caa37b0d-3ac3-4da3-bb09-427d1ff0fc77)
![IMG_7568](https://github.com/Monash-Connected-Autonomous-Vehicle/mcav-autoware.universe/assets/110092516/f9c5e71b-8e68-492f-b68c-c80813ae8f5a)
When erasing disk and installing Ubuntu, it gave me an Input/output error. I tried clicking the buttons but it was unresponsive so I'm stuck on this error message and can't get out of it
Maybe we could partition the 2TB NAS drive instead

**Comment by andSoHenceforth** [comment]
@hubdwoo has installed Ubuntu 22.04 on the Beast last evening. Can be treated as a new fresh installation. Likely didn't work because 500GB drive seemed to be broken. Task is solved and complete

**Comment by dylan-gonzalez** [comment]
What is the name of this partition?

**Comment by hubdwoo** [comment]
@dylan-gonzalez the device name?
