### ISSUE TITLE
Airsim Autoware Setup

### ISSUE THREAD

**Issue by dylan-gonzalez** [Monash-Connected-Autonomous-Vehicle/modified-autoware.universe#3]
Airsim is deprecated - Josh 🤷‍♀️

@hubdwoo can you close this issue please just with a few details as to why we shouldn't pursue Airsim (in case we ever think of trying to use it again)?

**Comment by hubdwoo** [comment]
## What I found:

---

General Idea

- There is 2 AirSim, one is the old deprecated version called “AirSim” and the updated one is called “Microsoft Project AirSim”.
- It is more focused on Aerial simulator. Simulating Drones and how they can use drones to fly itself. By fitting some model using the simulator
- Project AirSim is not available to the public just yet

AirSim (Deprecated)

- Runs on UE 4
- It is fully open source since now its deprecated
- Can collect training data
- Since its built on UE, you can use C++ to retrieve data that the simulator’s sensors are getting
- The sensors they have
    - Camera (Must have)
    - Barometer
    - Imu
    - GPS
    - Magnetometer
    - Distance Sensor
    - Lidar
    - Can generate Infrared Images

Possible ways to incorporate this to our Sim:

- Create a parent component for sensors
    - Create child components to simulate sensors
- In order to do this we might have to scrape VR
    - VR environment is very restricting
- Since AirSim is more focused on drones, we can use our sim to focus more in land based vehicles

14-09-23

- AirSim has a plugin but its running in Unreal Engine 4.
- Found out there is a way to execute a function in certain threads
- The car code is in CPP under PawnSimApi.cpp
